### ISSUE TITLE
Outbound link tracking prevents external links to open in new tab

### ISSUE THREAD

**Issue by jaimeiniesta** [plausible/plausible-tracker#38] opened 2022-06-08 14:40 UTC
## Versions

- 0.3.8

## Describe the bug

When using `enableAutoOutboundTracking`, external links that have `target="_blank"` don't open in a new tab. 

## Expected behavior

The links should open in a new tab.

## Steps to reproduce

Steps:
1. Install normally
2. Set it up like:

```
import Plausible from 'plausible-tracker'

const { enableAutoPageviews, enableAutoOutboundTracking } = Plausible({
    domain: 'example.com',
    trackLocalhost: false
  })

// This tracks the current page view and all future ones as well (for JS navigation)
enableAutoPageviews()

// This tracks outbound links
enableAutoOutboundTracking()
```

3. Try clicking an external link like `<a href="example.com" target="_blank">link</a>`.

## Your Environment

 - Browser [e.g. chrome, firefox]

## Additional context

Disabling `enableAutoPageviews()` makes it work fine again.

**Comment by metmarkosaric** [comment] 2022-06-08 14:43
thanks for reporting @jaimeiniesta! this seems like a duplicate of https://github.com/plausible/plausible-tracker/issues/12

**Comment by ukutaht** [comment] 2022-06-09 22:05
Thanks for reporting 🙏

Let's keep the discussion in #12. Subscribe to that issue for updates.

**Closed by ukutaht** 2022-06-09 22:06 UTC
Labels: bug
